### ISSUE TITLE
add better error handling

### ISSUE THREAD

**Issue by mjhea0** [mjhea0/flask-redis-queue#1]
Add error handlers on both the client in the AJAX requests as well as on the server for failed jobs.

**Comment by ibrahimsharaf** [comment]
Hi @mjhea0, how can I start on this one?

**Comment by mjhea0** [comment]
@ibrahimsharaf try thinking of some edge cases, and then add a test. For example, what would happen if the `task_type` is a string - like `hello` rather than an integer? Write a test for this and then add a `try/except` to the code to get the test to pass.

```python
def create_task(task_type):
    time.sleep(int(task_type) * 10)
    return True
```
