### ISSUE TITLE
Web repository does not exists

### ISSUE THREAD

**Issue by deepanshuagarwal150** [mjhea0/flask-redis-queue#4]
On using docker-compose up, it tries to pull web image which is not there and stops.

Pulling worker (web:)...
ERROR: pull access denied for web, repository does not exist or may require 'docker login'

**Comment by brandonserna** [comment]
If anyone else runs into this...

```sh
docker build . -t web
docker-compose up -d
```

Thanks for sharing this project @mjhea0 🎉

**Comment by mjhea0** [comment]
Thanks! 

```
docker-compose up -d --build
```

Should work as well. I just updated the readme
