### ISSUE TITLE
ID is the same for the list of task

### ISSUE THREAD

**Issue by AronWater** [mjhea0/flask-redis-queue#9]
![image](https://user-images.githubusercontent.com/36737465/77466201-e2cae280-6e44-11ea-829b-9a9d013f0882.png)
Am I experience a bug?
Why the id is all the same?
Thanks!

**Comment by mjhea0** [comment]
Because it's just checking the status of the same task. When you kick off the a new task, it will continue to check the status of that task until it finishes.
